myweb/login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='Login/log_in.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='SignUp'),
]

myweb/myweb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('', include('myweb_main.urls')),
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('social-login/', include('allauth.urls')),

]

myweb/myweb_main/urls.py
from django.urls import path
from .views import NoticeViews, QuestionViews, AnswerViews, CommentViews, VoteViews, HomeViews, MovieViews, GameViews

app_name = 'myweb'

urlpatterns = [

    # home 화면 url
    path('', HomeViews.homeList, name='home'),

    # 공지사항 url
    path('myweb-Notice/', NoticeViews.NoticeList, name='NoList'),
    path('myweb-Notice/<int:notice_id>/', NoticeViews.NoticeDetail, name='NoDetail'),
    path('myweb-Notice/NoCreate/', NoticeViews.NoticeCreate, name='NoCreate'),
    path('myweb-Notice/NoModify/<int:notice_id>/', NoticeViews.NoticeModify, name='NoModify'),
    path('myweb-Notice/NoDelete/<int:notice_id>/', NoticeViews.NoticeDelete, name='NoDelete'),
    path('myweb-Notice/download/<notice_id>', NoticeViews.NoticeFileDownload, name="NoFileDownload"),

    # 질문 url
    path('myweb-QnA/', QuestionViews.QuestionList, name='QList'), # 질문 리스트
    path('myweb-Q/<int:question_id>/', QuestionViews.QuestionDetail, name='QDetail'), # 질문 상세
    path('myweb-Q/QCreate/', QuestionViews.QuestionCreate, name='QCreate'), # 질문 작성
    path('myweb-Q/QModify/<int:question_id>/', QuestionViews.QuestionModify, name='QModify'), # 질문 수정
    path('myweb-Q/QDelete/<int:question_id>/', QuestionViews.QuestionDelete, name='QDelete'), # 질문 삭제
    path('myweb-Q/download/<question_id>', QuestionViews.QuestionFileDownload, name="QFileDownload"), # 파일

    # 답변 url
    path('myweb-A/ACreate/<int:question_id>/', AnswerViews.AnswerCreate, name='ACreate'), # 답변 작성
    path('myweb-A/AModify/<int:answer_id>/', AnswerViews.AnswerModify, name='AModify'), # 답변 수정
    path('myweb-A/ADelete/<int:answer_id>/', AnswerViews.AnswerDelete, name='ADelete'), # 답변 삭제

    # 질문 댓글 url
    path('myweb-Q/QCreate/Comment/<int:question_id>/', CommentViews.CommentCreateQuestion, name='CommentCreateQuestion'), # 댓글 등록 시 질문의 id인 question_id가 필요함
    path('myweb-Q/QModify/Comment/<int:comment_id>/', CommentViews.CommentModifyQuestion, name='CommentModifyQuestion'), # 수정이나 삭제 시에는 댓글의 id인 comment_id가 필요함
    path('myweb-Q/QDelete/Comment/<int:comment_id>/', CommentViews.CommentDeleteQuestion, name='CommentDeleteQuestion'),

    # 추천 url
    path('QVote/<int:question_id>/', VoteViews.VoteQusetion, name='QVote'),
    path('AVote/<int:answer_id>/', VoteViews.VoteAnswer, name='AVote'),
    path('NoVote/<int:notice_id>/', VoteViews.VoteNotice, name='NoVote'),
    path('MoVote/<int:movie_id>/', VoteViews.VoteMovie, name='MoVote'),
    path('GVote/<int:game_id>/', VoteViews.VoteGame, name='GVote'),

    # 영화 url
    path('myweb-Movie/', MovieViews.MovieList, name='MoList'),
    path('myweb-Movie/<int:movie_id>/', MovieViews.MovieDetail, name='MoDetail'),
    path('myweb-Movie/MoCreate/', MovieViews.MovieCreate, name='MoCreate'),
    path('myweb-Movie/MoModify/<int:movie_id>/', MovieViews.MovieModify, name='MoModify'),
    path('myweb-Movie/MoDelete/<int:movie_id>/', MovieViews.MovieDelete, name='MoDelete'),
    path('myweb-Movie/download/<movie_id>', MovieViews.MovieFileDownload, name="MoFileDownload"),
    # 영화 댓글 url
    path('myweb-Movie/MoCreate/Comment/<int:movie_id>/', CommentViews.CommentCreateMovie, name='CommentCreateMovie'),
    path('myweb-Movie/MoModify/Comment/<int:comment_id>/', CommentViews.CommentModifyMovie, name='CommentModifyMovie'),
    path('myweb-Movie/MoDelete/Comment/<int:comment_id>/', CommentViews.CommentDeleteMovie, name='CommentDeleteMovie'),

    # 게임 url
    path('myweb-Game/', GameViews.GameList, name='GList'),
    path('myweb-Game/<int:game_id>/', GameViews.GameDetail, name='GDetail'),
    path('myweb-Game/GCreate/', GameViews.GameCreate, name='GCreate'),
    path('myweb-Game/GModify/<int:game_id>/', GameViews.GameModify, name='GModify'),
    path('myweb-Game/GDelete/<int:game_id>/', GameViews.GameDelete, name='GDelete'),
    path('myweb-Game/download/<game_id>', GameViews.GameFileDownload, name="MoFileDownload"),
    # 게임 댓글 url
    path('myweb-Game/GCreate/Comment/<int:game_id>/', CommentViews.CommentCreateGame, name='CommentCreateGame'),
    path('myweb-Game/GModify/Comment/<int:comment_id>/', CommentViews.CommentModifyGame, name='CommentModifyGame'),
    path('myweb-Game/GDelete/Comment/<int:comment_id>/', CommentViews.CommentDeleteGame, name='CommentDeleteGame'),

]

myweb/myweb_main/models.py
import os
from uuid import uuid4

from django.conf import settings
from django.db import models
from django.utils import timezone

# 파일 경로
def FilePath(instance, filename):
    # upload_to="%Y/%m/%d" 처럼 날짜로 세분화
    ymd_path = timezone.now().strftime('%Y/%m/%d')
    # 길이 32 인 uuid 값
    uuid_name = uuid4().hex
    # 확장자 추출
    extension = os.path.splitext(filename)[-1].lower()
    # 결합 후 return
    return '/'.join([ymd_path, uuid_name + extension])

# 공지사항 model
class Notice(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)  # 기존 모델을 속성으로 가져갈 경우 ForeignKey를 사용, on_delete=models.CASCADE 공지가 삭제 될 경우 삭제
    subject = models.CharField(max_length=100, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True) # null=True, blank=True을 사용하면 어떤 조건으로든 값을 비워둘수 있음
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='NoVoter')  # 추천인 기능 (Notice 모델에서 사용한 author와 voter가 모두 settings.AUTH_USER_MODEL모델로 참조되고 있기 때문에 related_name을 써주어야 함)
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):  # id 대신 제목을 표시
        return self.subject

    class Meta:
        db_table = "공지사항"
        verbose_name = "공지사항"
        verbose_name_plural = "공지사항"


# 질문 model
class Question(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='QVoter')
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):
        return self.subject

    class Meta:
        db_table = "질문게시판"
        verbose_name = "질문게시판"
        verbose_name_plural = "질문게시판"


# 답변 model
class Answer(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    question = models.ForeignKey(Question, verbose_name="질문아이디", on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='AVoter')

    class Meta:
        db_table = "질문에대한답변"
        verbose_name = "질문에대한답변"
        verbose_name_plural = "질문에대한답변"


# 영화 게시판 model
class Movie(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    subject = models.CharField(verbose_name="제목", max_length=100)
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='MoVoter')
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):
        return self.subject

    def delete(self, *args, **kargs):
        if self.upload_file:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_file.path))
        super(Movie, self).delete(*args, **kargs)

    class Meta:
        db_table = "영화게시판"
        verbose_name = "영화게시판"
        verbose_name_plural = "영화게시판"


# 게임 게시판 model
class Game(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    subject = models.CharField(verbose_name="제목", max_length=100)
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='GVoter')
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):
        return self.subject

    class Meta:
        db_table = "게임게시판"
        verbose_name = "게임게시판"
        verbose_name_plural = "게임게시판"


# 댓글 model
class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    question = models.ForeignKey(Question, verbose_name="질문댓글", null=True, blank=True, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, verbose_name="영화댓글", null=True, blank=True, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, verbose_name="게임댓글", null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        db_table = "댓글"
        verbose_name = "댓글"
        verbose_name_plural = "댓글"

myweb/templates/QnA/comment_create.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글 등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "Errors/form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글 내용</label>
            <textarea class="form-control"name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">저장하기</button>
            </div>
    </form>
</div>
{% endblock %}

myweb/templates/QnA/question_detail.html
{% extends "main/base.html" %}
{% block title %} question_detail.html {% endblock title %}
{% block content %}
<div id="content">
    <!-- 사용자 오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}

    <h2 class="border-bottom ml-3 py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <!-- 질문 -->
        <div class="col-11" style="float:none; margin:0 auto">
            <div class="card">
                <div class="shadow card-body">
                    <div class="d-flex justify-content-start">
                        <h5 class="mr-2">{{ question.author.username }}</h5>
                        {% if question.modify_date %}
                        <p><small>(수정 : {{ question.modify_date | date:'Y-m-d H:i:s' }})</small></p>
                        {% else %}
                        <p><small>({{ question.create_date | date:'Y-m-d H:i:s' }})</small></p>
                        {% endif %}

                        <div class="ml-auto">
                            추천수&nbsp;:&nbsp;{{ question.voter.count }}&nbsp;
                            조회수&nbsp;:&nbsp;{{ question.hits }}
                        </div>
                    </div>
                    {% if question.upload_file %}
                    <div class="text-right">
                        <span>첨부파일&nbsp;:&nbsp;</span>
                        <a href="{% url 'myweb:QFileDownload' question.id %}" >{{ question.file_subject | truncatechars:20 }}</a>
                    </div>
                    {% endif %}

                    <div class="card-text">{{ question.content | safe }}</div>

                    <div class="d-flex justify-content-end">
                    <a href="#" data-uri="{% url 'myweb:QVote' question.id  %}" class="recommend btn btn-outline-secondary mr-2">추천</a>
                    {% if request.user == question.author %}
                        <a href="{% url 'myweb:QModify' question.id  %}" class="btn btn-outline-secondary ">수정</a>
                        <a href="#" class="delete btn btn-outline-secondary mx-2" data-uri="{% url 'myweb:QDelete' question.id  %}">삭제</a>
                    {% endif %}
                    <a href="{% url 'myweb:QList' %}"class="btn btn-outline-secondary">목록</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom ml-3 py-2">{{ question.comment_set.count }}&nbsp;개의 댓글이 있습니다.</h5>
    <div class="row my-3">
        <div class="col-11 mt-3" style="float:none; margin:0 auto">
            <div class="shadow card">
                <div id="more_comment">
                <!-- 질문댓글 -->
                {% if question.comment_set.count > 0 %}
                {% for comment in question.comment_set.all %}
                <a name="comment_{{ comment.id }}"></a>
                <div class="border-bottom">
                    <div class="mx-3 my-3">
                        <div class="d-flex justify-content-start">
                            <h5 class="mr-2">{{ comment.author }}</h5>
                            {% if comment.modify_date %}
                            <p><small>(수정 : {{ comment.modify_date | date:'Y-m-d H:i:s' }})</small></p>
                            {% else %}
                            <p><small>{{ comment.create_date | date:'Y-m-d H:i:s' }}</small></p>
                            {% endif %}
                        </div>

                        <span>{{ comment.content | linebreaksbr }}</span>
                    </div>

                    {% if request.user == comment.author %}
                    <div class="d-flex justify-content-end my-3">
                        <a href="{% url 'myweb:CommentModifyQuestion' comment.id %}" class="btn btn-outline-secondary mr-2">수정</a>
                        <a href="#" class="delete btn btn-outline-secondary mr-3" data-uri="{% url 'myweb:CommentDeleteQuestion' comment.id  %}">삭제</a>
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
                {% endif %}
                </div>

                {% if question.comment_set.count %}
                <div id="hide_more_button" style="cursor:pointer;">
                    <a id=hide_button_count>&nbsp;댓글 접기 &middot;&nbsp;{{ question.comment_set.count }}개의 댓글<br></a>
                </div>
                <div id="show_more_button" style="display:none;cursor:pointer;">
                    <a id="show_button_count">&nbsp;댓글 펼치기 &middot;&nbsp;{{ question.comment_set.count }}개의 댓글<br></a>
                </div>
                {% else %}
                <div id="hide_more_button" style="cursor:pointer;">
                    <a id=hide_button_count><br></a>
                </div>
                <div id="show_more_button" style="display:none;cursor:pointer;">
                    <a id="show_button_count"><br></a>
                </div>
                {% endif %}

                <!-- 댓글 양식 -->
                <div class="container my-3">
                    <form action="{% url 'myweb:CommentCreateQuestion' question.id %}" method="post" class="my-3">
                        {% csrf_token %}
                        {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {% for field in form %}
                            {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                            {% endif %}
                            {% endfor %}
                        </div>
                        {% endif %}
                        <div class="form-group">
                    <textarea {% if not user.is_authenticated %}disabled{% endif %}
                          name="content" class="form-control" rows="2"></textarea>
                        </div>
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-outline-secondary">등록</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
    <h5 class="border-bottom ml-3 py-2">{{ question.answer_set.count }}&nbsp;개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <!-- 앵커 태그 -->
    <a name="answer_{{ answer.id }}"></a>

    <div class="row my-3">
        <!-- 답변 -->
        <div class="col-11" style="float:none; margin:0 auto">
            <div class="card">
                <div class="shadow card-body">
                    <div class="d-flex justify-content-start">
                        <h5 class="mr-2">{{ answer.author.username }}</h5>
                        {% if answer.modify_date %}
                        <p><small>(수정 : {{ answer.modify_date | date:'Y-m-d H:i:s' }})</small></p>
                        {% else %}
                        <p><small>({{ answer.create_date | date:'Y-m-d H:i:s' }})</small></p>
                        {% endif %}

                        <div class="ml-auto">
                            추천수 : {{ answer.voter.count }}
                        </div>
                    </div>
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content | linebreaksbr }}</div>
                    
                    <div class="d-flex justify-content-end">
                        <a href="#" data-uri="{% url 'myweb:AVote' answer.id  %}" class="recommend btn btn-outline-secondary">추천</a>
                    {% if request.user == answer.author %}
                        <a href="{% url 'myweb:AModify' answer.id  %}" class="btn btn-outline-secondary mx-2">수정</a>
                        <a href="#" class="delete btn btn-outline-secondary " data-uri="{% url 'myweb:ADelete' answer.id  %}">삭제</a>
                    </div>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

<div class="row my-3">
    <div class="col-11" style="float:none; margin:0 auto">
        <div class="card">
            <div class="shadow card-body">
                <form action="{% url 'myweb:ACreate' question.id %}" method="post" class="my-3">
                    {% csrf_token %}
                    {% if form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for field in form %}
                        {% if field.errors %}
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class="form-group">
                        <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" class="form-control" rows="8"></textarea>
                    </div>
                    <div class="d-flex justify-content-end">
                        <input type="submit" value="등록" class="btn btn-outline-secondary">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() { // 삭제 버튼
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() { // 추천 버튼
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $('#hide_more_button').click(function(){ // 댓글 접기
        $('#more_comment').hide();
        $('#show_more_button').show();
        $('#hide_more_button').hide();
    });
    $('#show_more_button').click(function(){ // 댓글 펼치기
        $('#more_comment').show();
        $('#show_more_button').hide();
        $('#hide_more_button').show();
    });
});
</script>
{% endblock %}

myweb/templates/QnA/question_list.html
{% extends "main/base.html" %}
{% block title %} question_list.html {% endblock title %}
{% load myweb_filter %}
{% block content %}
<div class="container">
    <div class="row justify-content-between my-3">  <!-- 양쪽정렬 justify-content-between로 변경 -->
        <!--정렬-->
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
                <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>
                <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>
            </select>
        </div>
        <!--찾기-->
        <div class="input-group col-4">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>

    <table class="table table-bordered table-hover">
        <thead>
        <tr class="text-center thead-light">
            <th>번호</th>
            <th>추천</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
            <th>조회수</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center clickAble" style="cursor:pointer;" data-href="{% url 'myweb:QDetail' question.id %}">
            <td>
                <!--게시글 번호 -> 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>

            <!-- 추천 -->
            <td>
                {% if question.voter.all.count > 0 %}
                <span class="badge badge-warning px-2 py-1">{{ question.voter.all.count }}</span>
                {% endif %}
            </td>

            <td class="text-left">
                {{ question.subject | truncatechars:40  }}
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.author.username }}</td>
            <td>{{ question.create_date | date:'Y-m-d H:i' }}</td>
            <td>{{ question.hits }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="6">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <div class="d-flex justify-content-end">
        <a href="{% url 'myweb:QCreate' %}" class="btn btn-outline-secondary">게시글 작성</a>
    </div>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        <!-- 5만큼 작은 것 부터 5만큼 큰 것 까지만 표시 -->
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
</div>
<!--검색, 정렬 폼-->
<form id="searchForm" method="get" action="{% url 'myweb:QList' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() { // page-link 클릭 시 스크립트 실행
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    $("#btn_search").on('click', function() { // 검색버튼을 클릭하면 검색어 텍스트창에 입력된 값을 폼 kw필드에 설정하여 폼을 요청
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    $(".so").on('change', function() { // so라는 클래스를 가지고 있는 select박스의 값이 변경되면 선택된 값을 so 필드에 설정하여 폼 요청
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
    $(document).on('click','.clickAble',function() {
    window.location=$(this).data("href");
    });
});
</script>
{% endblock %}