myweb/login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='Login/log_in.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='SignUp'),
]

myweb/myweb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('', include('myweb_main.urls')),
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('social-login/', include('allauth.urls')),

]

myweb/myweb_main/urls.py
from django.urls import path
from .views import NoticeViews, QuestionViews, AnswerViews, CommentViews, VoteViews, HomeViews, MovieViews, GameViews

app_name = 'myweb'

urlpatterns = [

    # home 화면 url
    path('', HomeViews.homeList, name='home'),

    # 공지사항 url
    path('myweb-Notice/', NoticeViews.NoticeList, name='NoList'),
    path('myweb-Notice/<int:notice_id>/', NoticeViews.NoticeDetail, name='NoDetail'),
    path('myweb-Notice/NoCreate/', NoticeViews.NoticeCreate, name='NoCreate'),
    path('myweb-Notice/NoModify/<int:notice_id>/', NoticeViews.NoticeModify, name='NoModify'),
    path('myweb-Notice/NoDelete/<int:notice_id>/', NoticeViews.NoticeDelete, name='NoDelete'),
    path('myweb-Notice/download/<notice_id>', NoticeViews.NoticeFileDownload, name="NoFileDownload"),

    # 질문 url
    path('myweb-QnA/', QuestionViews.QuestionList, name='QList'), # 질문 리스트
    path('myweb-Q/<int:question_id>/', QuestionViews.QuestionDetail, name='QDetail'), # 질문 상세
    path('myweb-Q/QCreate/', QuestionViews.QuestionCreate, name='QCreate'), # 질문 작성
    path('myweb-Q/QModify/<int:question_id>/', QuestionViews.QuestionModify, name='QModify'), # 질문 수정
    path('myweb-Q/QDelete/<int:question_id>/', QuestionViews.QuestionDelete, name='QDelete'), # 질문 삭제
    path('myweb-Q/download/<question_id>', QuestionViews.QuestionFileDownload, name="QFileDownload"), # 파일

    # 답변 url
    path('myweb-A/ACreate/<int:question_id>/', AnswerViews.AnswerCreate, name='ACreate'), # 답변 작성
    path('myweb-A/AModify/<int:answer_id>/', AnswerViews.AnswerModify, name='AModify'), # 답변 수정
    path('myweb-A/ADelete/<int:answer_id>/', AnswerViews.AnswerDelete, name='ADelete'), # 답변 삭제

    # 질문 댓글 url
    path('myweb-Q/QCreate/Comment/<int:question_id>/', CommentViews.CommentCreateQuestion, name='CommentCreateQuestion'), # 댓글 등록 시 질문의 id인 question_id가 필요함
    path('myweb-Q/QModify/Comment/<int:comment_id>/', CommentViews.CommentModifyQuestion, name='CommentModifyQuestion'), # 수정이나 삭제 시에는 댓글의 id인 comment_id가 필요함
    path('myweb-Q/QDelete/Comment/<int:comment_id>/', CommentViews.CommentDeleteQuestion, name='CommentDeleteQuestion'),

    # 추천 url
    path('QVote/<int:question_id>/', VoteViews.VoteQusetion, name='QVote'),
    path('AVote/<int:answer_id>/', VoteViews.VoteAnswer, name='AVote'),
    path('NoVote/<int:notice_id>/', VoteViews.VoteNotice, name='NoVote'),
    path('MoVote/<int:movie_id>/', VoteViews.VoteMovie, name='MoVote'),
    path('GVote/<int:game_id>/', VoteViews.VoteGame, name='GVote'),

    # 영화 url
    path('myweb-Movie/', MovieViews.MovieList, name='MoList'),
    path('myweb-Movie/<int:movie_id>/', MovieViews.MovieDetail, name='MoDetail'),
    path('myweb-Movie/MoCreate/', MovieViews.MovieCreate, name='MoCreate'),
    path('myweb-Movie/MoModify/<int:movie_id>/', MovieViews.MovieModify, name='MoModify'),
    path('myweb-Movie/MoDelete/<int:movie_id>/', MovieViews.MovieDelete, name='MoDelete'),
    path('myweb-Movie/download/<movie_id>', MovieViews.MovieFileDownload, name="MoFileDownload"),
    # 영화 댓글 url
    path('myweb-Movie/MoCreate/Comment/<int:movie_id>/', CommentViews.CommentCreateMovie, name='CommentCreateMovie'),
    path('myweb-Movie/MoModify/Comment/<int:comment_id>/', CommentViews.CommentModifyMovie, name='CommentModifyMovie'),
    path('myweb-Movie/MoDelete/Comment/<int:comment_id>/', CommentViews.CommentDeleteMovie, name='CommentDeleteMovie'),

    # 게임 url
    path('myweb-Game/', GameViews.GameList, name='GList'),
    path('myweb-Game/<int:game_id>/', GameViews.GameDetail, name='GDetail'),
    path('myweb-Game/GCreate/', GameViews.GameCreate, name='GCreate'),
    path('myweb-Game/GModify/<int:game_id>/', GameViews.GameModify, name='GModify'),
    path('myweb-Game/GDelete/<int:game_id>/', GameViews.GameDelete, name='GDelete'),
    path('myweb-Game/download/<game_id>', GameViews.GameFileDownload, name="MoFileDownload"),
    # 게임 댓글 url
    path('myweb-Game/GCreate/Comment/<int:game_id>/', CommentViews.CommentCreateGame, name='CommentCreateGame'),
    path('myweb-Game/GModify/Comment/<int:comment_id>/', CommentViews.CommentModifyGame, name='CommentModifyGame'),
    path('myweb-Game/GDelete/Comment/<int:comment_id>/', CommentViews.CommentDeleteGame, name='CommentDeleteGame'),

]

myweb/myweb_main/models.py
import os
from uuid import uuid4

from django.conf import settings
from django.db import models
from django.utils import timezone

# 파일 경로
def FilePath(instance, filename):
    # upload_to="%Y/%m/%d" 처럼 날짜로 세분화
    ymd_path = timezone.now().strftime('%Y/%m/%d')
    # 길이 32 인 uuid 값
    uuid_name = uuid4().hex
    # 확장자 추출
    extension = os.path.splitext(filename)[-1].lower()
    # 결합 후 return
    return '/'.join([ymd_path, uuid_name + extension])

# 공지사항 model
class Notice(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)  # 기존 모델을 속성으로 가져갈 경우 ForeignKey를 사용, on_delete=models.CASCADE 공지가 삭제 될 경우 삭제
    subject = models.CharField(max_length=100, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True) # null=True, blank=True을 사용하면 어떤 조건으로든 값을 비워둘수 있음
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='NoVoter')  # 추천인 기능 (Notice 모델에서 사용한 author와 voter가 모두 settings.AUTH_USER_MODEL모델로 참조되고 있기 때문에 related_name을 써주어야 함)
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):  # id 대신 제목을 표시
        return self.subject

    class Meta:
        db_table = "공지사항"
        verbose_name = "공지사항"
        verbose_name_plural = "공지사항"


# 질문 model
class Question(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='QVoter')
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):
        return self.subject

    class Meta:
        db_table = "질문게시판"
        verbose_name = "질문게시판"
        verbose_name_plural = "질문게시판"


# 답변 model
class Answer(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    question = models.ForeignKey(Question, verbose_name="질문아이디", on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='AVoter')

    class Meta:
        db_table = "질문에대한답변"
        verbose_name = "질문에대한답변"
        verbose_name_plural = "질문에대한답변"


# 영화 게시판 model
class Movie(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    subject = models.CharField(verbose_name="제목", max_length=100)
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='MoVoter')
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):
        return self.subject

    def delete(self, *args, **kargs):
        if self.upload_file:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_file.path))
        super(Movie, self).delete(*args, **kargs)

    class Meta:
        db_table = "영화게시판"
        verbose_name = "영화게시판"
        verbose_name_plural = "영화게시판"


# 게임 게시판 model
class Game(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    subject = models.CharField(verbose_name="제목", max_length=100)
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='GVoter')
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):
        return self.subject

    class Meta:
        db_table = "게임게시판"
        verbose_name = "게임게시판"
        verbose_name_plural = "게임게시판"


# 댓글 model
class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    question = models.ForeignKey(Question, verbose_name="질문댓글", null=True, blank=True, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, verbose_name="영화댓글", null=True, blank=True, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, verbose_name="게임댓글", null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        db_table = "댓글"
        verbose_name = "댓글"
        verbose_name_plural = "댓글"

myweb/myweb_main/views/MovieViews.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import MovieForm
from ..models import Movie

import urllib
import os
from django.http import HttpResponse, Http404

# 내용 출력
def MovieDetail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    session_cookie = request.user
    cookie_name = f'movie_hits:{session_cookie}'

    response = render(request, 'Movie/movie_detail.html', {'movie': movie})

    # 조회수 GET증가 방지 쿠키처리
    if request.COOKIES.get(cookie_name) is not None:
        cookies = request.COOKIES.get(cookie_name)
        cookies_list = cookies.split('|')
        if str(movie_id) not in cookies_list:
            response.set_cookie(cookie_name, cookies + f'|{movie_id}', expires=None)
            movie.hits += 1
            movie.save()
            return response

    else:
        response.set_cookie(cookie_name, movie_id, expires=None)
        movie.hits += 1
        movie.save()
        return response
    return response

# 목록 출력
def MovieList(request):
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지 값이 없을경우 디폴트 값은 1
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬하여 조회
    if so == 'recommend':
        movie_list = Movie.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        movie_list = Movie.objects.annotate(num_comment=Count('comment')).order_by('-num_comment', '-create_date')
    else:  # recent
        movie_list = Movie.objects.order_by('-create_date')

    # 검색
    if kw:
        movie_list = movie_list.filter(
            Q(subject__icontains=kw) |  # 제목검색 대소문자 구분 x (subject__contains=kw : 대소문자 구분)
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) # 글쓴이검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(movie_list, 8)  # 페이지당 8개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'movie_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'Movie/movie_list.html', context)

# 등록
@login_required(login_url='login:login')
def MovieCreate(request):
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.author = request.user
            if request.FILES:
                if 'upload_file' in request.FILES.keys():
                    movie.file_subject = request.FILES['upload_file'].name
            movie.create_date = timezone.now()
            movie.save()
            return redirect('myweb:MoList')
    else:
        form = MovieForm
    return render(request, 'Post/post_create.html', {'form': form})

# 수정
@login_required(login_url='login:login')
def MovieModify(request, movie_id):

    movie = get_object_or_404(Movie, pk=movie_id)
    if request.user != movie.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('myweb:MoDetail', movie_id=movie.id)

    if request.method == "POST":
        form = MovieForm(request.POST, request.FILES, instance=movie)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.author = request.user
            if request.FILES:
                if 'upload_file' in request.FILES.keys():
                    movie.file_subject = request.FILES['upload_file'].name
            movie.modify_date = timezone.now()
            movie.save()
            return redirect('myweb:MoDetail', movie_id=movie.id)
    else:
        form = MovieForm(instance=movie)
    return render(request, 'Post/post_create.html', {'form': form})

# 삭제
@login_required(login_url='login:login')
def MovieDelete(request, movie_id):

    movie = get_object_or_404(Movie, pk=movie_id)
    if request.user != movie.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('myweb:MoDetail', movie_id=movie.id)
    movie.delete()
    return redirect('myweb:MoList')

# 파일 다운로드
@login_required(login_url='login:login')
def MovieFileDownload(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    url = movie.upload_file.url[1:]

    if os.path.exists(url):
        with open(url, 'rb') as fh:
            quote_file_url = urllib.parse.quote(movie.file_subject.encode('utf-8'))
            response = HttpResponse(fh.read())
            response['Content-Disposition'] = 'attachment;filename*=UTF-8\'\'%s' % quote_file_url
            return response
        raise Http404

myweb/templates/Movie/movie_detail.html
{% extends "main/base.html" %}
{% block title %} movie_detail.html {% endblock title %}
{% block content %}
    <!-- 사용자 오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}

    <h2 class="border-bottom ml-3 py-2">{{ movie.subject }}</h2>
    <div class="row my-3">
        <!-- 질문 -->
        <div class="col-11" style="float:none; margin:0 auto">
            <div class="card">
                <div class="shadow card-body">
                    <div class="d-flex justify-content-start">
                        <h5 class="mr-2">{{ movie.author.username }}</h5>
                        {% if movie.modify_date %}
                        <p><small>(수정 : {{ movie.modify_date | date:'Y-m-d H:i:s' }})</small></p>
                        {% else %}
                        <p><small>({{ movie.create_date | date:'Y-m-d H:i:s' }})</small></p>
                        {% endif %}

                        <div class="ml-auto">
                            추천수&nbsp;:&nbsp;{{ movie.voter.count }}&nbsp;
                            조회수&nbsp;:&nbsp;{{ movie.hits }}
                        </div>
                    </div>
                    {% if movie.upload_file %}
                    <div class="text-right">
                        <span>첨부파일&nbsp;:&nbsp;</span>
                        <a href="{% url 'myweb:MoFileDownload' movie.id %}" >{{ movie.file_subject | truncatechars:20 }}</a>
                    </div>
                    {% endif %}

                    <div class="card-text">{{ movie.content | safe }}</div>

                    <div class="d-flex justify-content-end">
                    <a href="#" data-uri="{% url 'myweb:MoVote' movie.id  %}" class="recommend btn btn-outline-secondary mr-2">추천</a>
                    {% if request.user == movie.author %}
                        <a href="{% url 'myweb:MoModify' movie.id  %}" class="btn btn-outline-secondary ">수정</a>
                        <a href="#" class="delete btn btn-outline-secondary mx-2" data-uri="{% url 'myweb:MoDelete' movie.id  %}">삭제</a>
                    {% endif %}
                    <a href="{% url 'myweb:MoList' %}"class="btn btn-outline-secondary">목록</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom ml-3 py-2">{{ movie.comment_set.count }}&nbsp;개의 댓글이 있습니다.</h5>
    <div class="row my-3">
        <div class="col-11 mt-3" style="float:none; margin:0 auto">
            <div class="shadow card">
                <div id="more_comment">
                <!-- 댓글 -->
                {% if movie.comment_set.count > 0 %}
                {% for comment in movie.comment_set.all %}
                <a name="comment_{{ comment.id }}"></a>
                <div class="border-bottom">
                    <div class="mx-3 my-3">
                        <div class="d-flex justify-content-start">
                            <h5 class="mr-2">{{ comment.author }}</h5>
                            {% if comment.modify_date %}
                            <p><small>(수정 : {{ comment.modify_date | date:'Y-m-d H:i:s' }})</small></p>
                            {% else %}
                            <p><small>{{ comment.create_date | date:'Y-m-d H:i:s' }}</small></p>
                            {% endif %}
                        </div>

                        <span>{{ comment.content | linebreaksbr }}</span>
                    </div>

                    {% if request.user == comment.author %}
                    <div class="d-flex justify-content-end my-3">
                        <a href="{% url 'myweb:CommentModifyMovie' comment.id %}" class="btn btn-outline-secondary mr-2">수정</a>
                        <a href="#" class="delete btn btn-outline-secondary mr-3" data-uri="{% url 'myweb:CommentDeleteMovie' comment.id  %}">삭제</a>
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
                {% endif %}
                </div>

                <!-- 댓글 접기, 펼치기 -->
                {% if movie.comment_set.count %}
                <div id="hide_more_button" style="cursor:pointer;">
                    <a id=hide_button_count>&nbsp;댓글 접기 &middot;&nbsp;{{ movie.comment_set.count }}개의 댓글<br></a>
                </div>
                <div id="show_more_button" style="display:none;cursor:pointer;">
                    <a id="show_button_count">&nbsp;댓글 펼치기 &middot;&nbsp;{{ movie.comment_set.count }}개의 댓글<br></a>
                </div>
                {% else %}
                <div id="hide_more_button" style="cursor:pointer;">
                    <a id=hide_button_count><br></a>
                </div>
                <div id="show_more_button" style="display:none;cursor:pointer;">
                    <a id="show_button_count"><br></a>
                </div>
                {% endif %}

                <!-- 댓글 양식 -->
                <div class="container my-3">
                    <form action="{% url 'myweb:CommentCreateMovie' movie.id %}" method="post" class="my-3">
                        {% csrf_token %}
                        {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {% for field in form %}
                            {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                            {% endif %}
                            {% endfor %}
                        </div>
                        {% endif %}
                        <div class="form-group">
                <textarea {% if not user.is_authenticated %}disabled{% endif %}
                          name="content" id="con" class="form-control" rows="2"></textarea>
                        </div>
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-outline-secondary">등록</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() { // 삭제 버튼
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() { // 추천 버튼
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $('#hide_more_button').click(function(){ // 댓글 접기
        $('#more_comment').hide();
        $('#show_more_button').show();
        $('#hide_more_button').hide();
    });
    $('#show_more_button').click(function(){ // 댓글 펼치기
        $('#more_comment').show();
        $('#show_more_button').hide();
        $('#hide_more_button').show();
    });
});
</script>
{% endblock %}