myweb/login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='Login/log_in.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='SignUp'),
]

myweb/myweb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('', include('myweb_main.urls')),
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('social-login/', include('allauth.urls')),

]

myweb/myweb_main/urls.py
from django.urls import path
from .views import NoticeViews, QuestionViews, AnswerViews, CommentViews, VoteViews, HomeViews, MovieViews, GameViews

app_name = 'myweb'

urlpatterns = [

    # home 화면 url
    path('', HomeViews.homeList, name='home'),

    # 공지사항 url
    path('myweb-Notice/', NoticeViews.NoticeList, name='NoList'),
    path('myweb-Notice/<int:notice_id>/', NoticeViews.NoticeDetail, name='NoDetail'),
    path('myweb-Notice/NoCreate/', NoticeViews.NoticeCreate, name='NoCreate'),
    path('myweb-Notice/NoModify/<int:notice_id>/', NoticeViews.NoticeModify, name='NoModify'),
    path('myweb-Notice/NoDelete/<int:notice_id>/', NoticeViews.NoticeDelete, name='NoDelete'),
    path('myweb-Notice/download/<notice_id>', NoticeViews.NoticeFileDownload, name="NoFileDownload"),

    # 질문 url
    path('myweb-QnA/', QuestionViews.QuestionList, name='QList'), # 질문 리스트
    path('myweb-Q/<int:question_id>/', QuestionViews.QuestionDetail, name='QDetail'), # 질문 상세
    path('myweb-Q/QCreate/', QuestionViews.QuestionCreate, name='QCreate'), # 질문 작성
    path('myweb-Q/QModify/<int:question_id>/', QuestionViews.QuestionModify, name='QModify'), # 질문 수정
    path('myweb-Q/QDelete/<int:question_id>/', QuestionViews.QuestionDelete, name='QDelete'), # 질문 삭제
    path('myweb-Q/download/<question_id>', QuestionViews.QuestionFileDownload, name="QFileDownload"), # 파일

    # 답변 url
    path('myweb-A/ACreate/<int:question_id>/', AnswerViews.AnswerCreate, name='ACreate'), # 답변 작성
    path('myweb-A/AModify/<int:answer_id>/', AnswerViews.AnswerModify, name='AModify'), # 답변 수정
    path('myweb-A/ADelete/<int:answer_id>/', AnswerViews.AnswerDelete, name='ADelete'), # 답변 삭제

    # 질문 댓글 url
    path('myweb-Q/QCreate/Comment/<int:question_id>/', CommentViews.CommentCreateQuestion, name='CommentCreateQuestion'), # 댓글 등록 시 질문의 id인 question_id가 필요함
    path('myweb-Q/QModify/Comment/<int:comment_id>/', CommentViews.CommentModifyQuestion, name='CommentModifyQuestion'), # 수정이나 삭제 시에는 댓글의 id인 comment_id가 필요함
    path('myweb-Q/QDelete/Comment/<int:comment_id>/', CommentViews.CommentDeleteQuestion, name='CommentDeleteQuestion'),

    # 추천 url
    path('QVote/<int:question_id>/', VoteViews.VoteQusetion, name='QVote'),
    path('AVote/<int:answer_id>/', VoteViews.VoteAnswer, name='AVote'),
    path('NoVote/<int:notice_id>/', VoteViews.VoteNotice, name='NoVote'),
    path('MoVote/<int:movie_id>/', VoteViews.VoteMovie, name='MoVote'),
    path('GVote/<int:game_id>/', VoteViews.VoteGame, name='GVote'),

    # 영화 url
    path('myweb-Movie/', MovieViews.MovieList, name='MoList'),
    path('myweb-Movie/<int:movie_id>/', MovieViews.MovieDetail, name='MoDetail'),
    path('myweb-Movie/MoCreate/', MovieViews.MovieCreate, name='MoCreate'),
    path('myweb-Movie/MoModify/<int:movie_id>/', MovieViews.MovieModify, name='MoModify'),
    path('myweb-Movie/MoDelete/<int:movie_id>/', MovieViews.MovieDelete, name='MoDelete'),
    path('myweb-Movie/download/<movie_id>', MovieViews.MovieFileDownload, name="MoFileDownload"),
    # 영화 댓글 url
    path('myweb-Movie/MoCreate/Comment/<int:movie_id>/', CommentViews.CommentCreateMovie, name='CommentCreateMovie'),
    path('myweb-Movie/MoModify/Comment/<int:comment_id>/', CommentViews.CommentModifyMovie, name='CommentModifyMovie'),
    path('myweb-Movie/MoDelete/Comment/<int:comment_id>/', CommentViews.CommentDeleteMovie, name='CommentDeleteMovie'),

    # 게임 url
    path('myweb-Game/', GameViews.GameList, name='GList'),
    path('myweb-Game/<int:game_id>/', GameViews.GameDetail, name='GDetail'),
    path('myweb-Game/GCreate/', GameViews.GameCreate, name='GCreate'),
    path('myweb-Game/GModify/<int:game_id>/', GameViews.GameModify, name='GModify'),
    path('myweb-Game/GDelete/<int:game_id>/', GameViews.GameDelete, name='GDelete'),
    path('myweb-Game/download/<game_id>', GameViews.GameFileDownload, name="MoFileDownload"),
    # 게임 댓글 url
    path('myweb-Game/GCreate/Comment/<int:game_id>/', CommentViews.CommentCreateGame, name='CommentCreateGame'),
    path('myweb-Game/GModify/Comment/<int:comment_id>/', CommentViews.CommentModifyGame, name='CommentModifyGame'),
    path('myweb-Game/GDelete/Comment/<int:comment_id>/', CommentViews.CommentDeleteGame, name='CommentDeleteGame'),

]

myweb/myweb_main/models.py
import os
from uuid import uuid4

from django.conf import settings
from django.db import models
from django.utils import timezone

# 파일 경로
def FilePath(instance, filename):
    # upload_to="%Y/%m/%d" 처럼 날짜로 세분화
    ymd_path = timezone.now().strftime('%Y/%m/%d')
    # 길이 32 인 uuid 값
    uuid_name = uuid4().hex
    # 확장자 추출
    extension = os.path.splitext(filename)[-1].lower()
    # 결합 후 return
    return '/'.join([ymd_path, uuid_name + extension])

# 공지사항 model
class Notice(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)  # 기존 모델을 속성으로 가져갈 경우 ForeignKey를 사용, on_delete=models.CASCADE 공지가 삭제 될 경우 삭제
    subject = models.CharField(max_length=100, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True) # null=True, blank=True을 사용하면 어떤 조건으로든 값을 비워둘수 있음
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='NoVoter')  # 추천인 기능 (Notice 모델에서 사용한 author와 voter가 모두 settings.AUTH_USER_MODEL모델로 참조되고 있기 때문에 related_name을 써주어야 함)
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):  # id 대신 제목을 표시
        return self.subject

    class Meta:
        db_table = "공지사항"
        verbose_name = "공지사항"
        verbose_name_plural = "공지사항"


# 질문 model
class Question(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='QVoter')
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):
        return self.subject

    class Meta:
        db_table = "질문게시판"
        verbose_name = "질문게시판"
        verbose_name_plural = "질문게시판"


# 답변 model
class Answer(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    question = models.ForeignKey(Question, verbose_name="질문아이디", on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='AVoter')

    class Meta:
        db_table = "질문에대한답변"
        verbose_name = "질문에대한답변"
        verbose_name_plural = "질문에대한답변"


# 영화 게시판 model
class Movie(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    subject = models.CharField(verbose_name="제목", max_length=100)
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='MoVoter')
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):
        return self.subject

    def delete(self, *args, **kargs):
        if self.upload_file:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_file.path))
        super(Movie, self).delete(*args, **kargs)

    class Meta:
        db_table = "영화게시판"
        verbose_name = "영화게시판"
        verbose_name_plural = "영화게시판"


# 게임 게시판 model
class Game(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    subject = models.CharField(verbose_name="제목", max_length=100)
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='GVoter')
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):
        return self.subject

    class Meta:
        db_table = "게임게시판"
        verbose_name = "게임게시판"
        verbose_name_plural = "게임게시판"


# 댓글 model
class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    question = models.ForeignKey(Question, verbose_name="질문댓글", null=True, blank=True, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, verbose_name="영화댓글", null=True, blank=True, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, verbose_name="게임댓글", null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        db_table = "댓글"
        verbose_name = "댓글"
        verbose_name_plural = "댓글"

myweb/myweb_main/views/HomeViews.py
from django.shortcuts import render
from django.core.paginator import Paginator
from ..models import Question, Notice, Movie, Game

# home 화면 출력
def homeList(request):

    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지 값이 없을경우 디폴트 값은 1

    # 조회 결과를 역순으로 정렬
    HomeQnA_List = Question.objects.order_by('-create_date')
    HomeNotice_List = Notice.objects.order_by('-create_date')
    HomeMovie_List = Movie.objects.order_by('-create_date')
    HomeGame_List = Game.objects.order_by('-create_date')

    # 페이징처리 5개씩
    Paginator_QnA = Paginator(HomeQnA_List, 5)
    Paginator_Notice = Paginator(HomeNotice_List, 5)
    Paginator_Movie = Paginator(HomeMovie_List, 5)
    Paginator_Game = Paginator(HomeGame_List, 5)

    Page_Obj_QnA = Paginator_QnA.get_page(page)
    Page_Obj_Notice = Paginator_Notice.get_page(page)
    Page_Obj_Movie = Paginator_Movie.get_page(page)
    Page_Obj_Game = Paginator_Game.get_page(page)

    context = {'homeQnA_list': Page_Obj_QnA, 'homeNotice_list': Page_Obj_Notice, 'homeMovie_list': Page_Obj_Movie, 'homeGame_list': Page_Obj_Game}
    return render(request, 'main/home.html', context)

myweb/templates/main/base.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}konimel19-community{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %} {% endblock %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/summernote/summernote-lite.css' %}">

</head>
<body>
<nav class="navbar navbar-expand-md navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'myweb:home' %}">홈페이지</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item"><a class="nav-link" href="{% url 'myweb:NoList' %}">공지사항</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'myweb:QList' %}">QnA</a> </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">게시판</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'myweb:MoList' %}">영화</a>
                    <a class="dropdown-item" href="{% url 'myweb:GList' %}">게임</a>
                </div>
            </li>
            {% if user.is_superuser or user.is_admin %}
            <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a> </li>
            {% endif %}
        </ul>
        {% if user.is_authenticated %}
        <span class="navbar-text">환영합니다! {{ user.username }} 님 <a href="{% url 'login:logout' %}">로그아웃</a></span>
        {% else %}
        <span class="navbar-text">환영합니다! <a href="{% url 'login:login' %}">로그인</a> <a href="{%url 'login:SignUp' %}">회원가입</a></span>
        {% endif %}
    </div>

</nav>

{% block content %}{% endblock %}

<script src="{% static 'css/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'css/bootstrap.min.js' %}"></script>

<script src="{% static 'css/summernote/summernote-lite.js' %}"></script>
<script src="{% static 'css/summernote/lang/summernote-ko-KR.js' %}"></script>

{% block script %}
{% endblock %}

<footer class="border-top">
    &copy;; Lee Min Hyeok 2020.
</footer>

</body>
</html>

myweb/templates/main/home.html
{% extends "main/base.html" %}
{% block title %} home.html {% endblock title %}
{% load static %}
{% block content %}
<!-- 캐러셀 -->
<div class="row">
    <div id="homeCarousel" class="carousel slide col-md-6" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#homeCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#homeCarousel" data-slide-to="1"></li>
            <li data-target="#homeCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img src="{% static 'img/sample/sample1.jpg' %}" height="400" class="d-block w-100" alt="사진1">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/sample/sample2.jpg' %}" height="400"class="d-block w-100" alt="사진2">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/sample/sample3.jpg' %}" height="400"class="d-block w-100" alt="사진3">
            </div>
            <a class="carousel-control-prev" href="#homeCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#homeCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    <div class="flex-wrap col-sm">
        <div class="home">
            <h4><a href="{% url 'myweb:NoList' %}">공지사항</a></h4>
        </div>
        {% if homeNotice_list %}
        <table class="table-hover" width="100%">
            <tr class="border-top">
            {% for homeNotice in homeNotice_list %}
                <td class="clickAble dotted-line" style="cursor:pointer;" data-href="{% url 'myweb:NoDetail' homeNotice.id %}">
                    {{ homeNotice.subject | truncatechars:12 }}
                </td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <p>공지사항이 없습니다.</p>
        {% endif %}
        <div class="home">
            <h4><a class="home" href="{% url 'myweb:QList' %}">질문과 답변</a></h4>
        </div>
        {% if homeQnA_list %}
        <table class="table-hover" width="100%">
            <tr class="border-top">
            {% for homeQnA in homeQnA_list %}
                <td class="clickAble dotted-line" style="cursor:pointer;" data-href="{% url 'myweb:QDetail' homeQnA.id %}">
                    {{ homeQnA.subject | truncatechars:12 }}
                    {% if homeQnA.answer_set.count > 0 %}
                    <span class="text-danger small ml-2">{{ homeQnA.answer_set.count }}</span>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <p>질문이 없습니다.</p>
        {% endif %}
    </div>

    <div class="flex-wrap col-sm">
        <div class="home">
            <h4><a href="{% url 'myweb:MoList' %}">영화</a></h4>
        </div>
        {% if homeMovie_list %}
        <table class="table-hover" width="100%">
            <tr class="border-top">
            {% for homeMovie in homeMovie_list %}
                <td class="clickAble dotted-line" style="cursor:pointer;" data-href="{% url 'myweb:MoDetail' homeMovie.id %}">
                    {{ homeMovie.subject | truncatechars:12 }}
                    {% if homeMovie.comment_set.count > 0 %}
                    <span class="text-danger small ml-2">{{ homeMovie.comment_set.count }}</span>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <p>게시글이 없습니다.</p>
        {% endif %}

        <div class="home">
            <h4><a href="{% url 'myweb:GList' %}">게임</a></h4>
        </div>
        {% if homeGame_list %}
        <table class="table-hover" width="100%">
            <tr class="border-top">
            {% for homeGame in homeGame_list %}
                <td class="clickAble dotted-line" style="cursor:pointer;" data-href="{% url 'myweb:GDetail' homeGame.id %}">
                    {{ homeGame.subject | truncatechars:12 }}
                    {% if homeGame.comment_set.count > 0 %}
                    <span class="text-danger small ml-2">{{ homeGame.comment_set.count }}</span>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <p>게시글이 없습니다.</p>
        {% endif %}

    </div>
</div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(document).on('click','.clickAble',function() {
    window.location=$(this).data("href");
    });
});
</script>
{% endblock %}