myweb/login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='Login/log_in.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='SignUp'),
]

myweb/myweb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('', include('myweb_main.urls')),
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('social-login/', include('allauth.urls')),

]

myweb/myweb_main/urls.py
from django.urls import path
from .views import NoticeViews, QuestionViews, AnswerViews, CommentViews, VoteViews, HomeViews, MovieViews, GameViews

app_name = 'myweb'

urlpatterns = [

    # home 화면 url
    path('', HomeViews.homeList, name='home'),

    # 공지사항 url
    path('myweb-Notice/', NoticeViews.NoticeList, name='NoList'),
    path('myweb-Notice/<int:notice_id>/', NoticeViews.NoticeDetail, name='NoDetail'),
    path('myweb-Notice/NoCreate/', NoticeViews.NoticeCreate, name='NoCreate'),
    path('myweb-Notice/NoModify/<int:notice_id>/', NoticeViews.NoticeModify, name='NoModify'),
    path('myweb-Notice/NoDelete/<int:notice_id>/', NoticeViews.NoticeDelete, name='NoDelete'),
    path('myweb-Notice/download/<notice_id>', NoticeViews.NoticeFileDownload, name="NoFileDownload"),

    # 질문 url
    path('myweb-QnA/', QuestionViews.QuestionList, name='QList'), # 질문 리스트
    path('myweb-Q/<int:question_id>/', QuestionViews.QuestionDetail, name='QDetail'), # 질문 상세
    path('myweb-Q/QCreate/', QuestionViews.QuestionCreate, name='QCreate'), # 질문 작성
    path('myweb-Q/QModify/<int:question_id>/', QuestionViews.QuestionModify, name='QModify'), # 질문 수정
    path('myweb-Q/QDelete/<int:question_id>/', QuestionViews.QuestionDelete, name='QDelete'), # 질문 삭제
    path('myweb-Q/download/<question_id>', QuestionViews.QuestionFileDownload, name="QFileDownload"), # 파일

    # 답변 url
    path('myweb-A/ACreate/<int:question_id>/', AnswerViews.AnswerCreate, name='ACreate'), # 답변 작성
    path('myweb-A/AModify/<int:answer_id>/', AnswerViews.AnswerModify, name='AModify'), # 답변 수정
    path('myweb-A/ADelete/<int:answer_id>/', AnswerViews.AnswerDelete, name='ADelete'), # 답변 삭제

    # 질문 댓글 url
    path('myweb-Q/QCreate/Comment/<int:question_id>/', CommentViews.CommentCreateQuestion, name='CommentCreateQuestion'), # 댓글 등록 시 질문의 id인 question_id가 필요함
    path('myweb-Q/QModify/Comment/<int:comment_id>/', CommentViews.CommentModifyQuestion, name='CommentModifyQuestion'), # 수정이나 삭제 시에는 댓글의 id인 comment_id가 필요함
    path('myweb-Q/QDelete/Comment/<int:comment_id>/', CommentViews.CommentDeleteQuestion, name='CommentDeleteQuestion'),

    # 추천 url
    path('QVote/<int:question_id>/', VoteViews.VoteQusetion, name='QVote'),
    path('AVote/<int:answer_id>/', VoteViews.VoteAnswer, name='AVote'),
    path('NoVote/<int:notice_id>/', VoteViews.VoteNotice, name='NoVote'),
    path('MoVote/<int:movie_id>/', VoteViews.VoteMovie, name='MoVote'),
    path('GVote/<int:game_id>/', VoteViews.VoteGame, name='GVote'),

    # 영화 url
    path('myweb-Movie/', MovieViews.MovieList, name='MoList'),
    path('myweb-Movie/<int:movie_id>/', MovieViews.MovieDetail, name='MoDetail'),
    path('myweb-Movie/MoCreate/', MovieViews.MovieCreate, name='MoCreate'),
    path('myweb-Movie/MoModify/<int:movie_id>/', MovieViews.MovieModify, name='MoModify'),
    path('myweb-Movie/MoDelete/<int:movie_id>/', MovieViews.MovieDelete, name='MoDelete'),
    path('myweb-Movie/download/<movie_id>', MovieViews.MovieFileDownload, name="MoFileDownload"),
    # 영화 댓글 url
    path('myweb-Movie/MoCreate/Comment/<int:movie_id>/', CommentViews.CommentCreateMovie, name='CommentCreateMovie'),
    path('myweb-Movie/MoModify/Comment/<int:comment_id>/', CommentViews.CommentModifyMovie, name='CommentModifyMovie'),
    path('myweb-Movie/MoDelete/Comment/<int:comment_id>/', CommentViews.CommentDeleteMovie, name='CommentDeleteMovie'),

    # 게임 url
    path('myweb-Game/', GameViews.GameList, name='GList'),
    path('myweb-Game/<int:game_id>/', GameViews.GameDetail, name='GDetail'),
    path('myweb-Game/GCreate/', GameViews.GameCreate, name='GCreate'),
    path('myweb-Game/GModify/<int:game_id>/', GameViews.GameModify, name='GModify'),
    path('myweb-Game/GDelete/<int:game_id>/', GameViews.GameDelete, name='GDelete'),
    path('myweb-Game/download/<game_id>', GameViews.GameFileDownload, name="MoFileDownload"),
    # 게임 댓글 url
    path('myweb-Game/GCreate/Comment/<int:game_id>/', CommentViews.CommentCreateGame, name='CommentCreateGame'),
    path('myweb-Game/GModify/Comment/<int:comment_id>/', CommentViews.CommentModifyGame, name='CommentModifyGame'),
    path('myweb-Game/GDelete/Comment/<int:comment_id>/', CommentViews.CommentDeleteGame, name='CommentDeleteGame'),

]

myweb/myweb_main/models.py
import os
from uuid import uuid4

from django.conf import settings
from django.db import models
from django.utils import timezone

# 파일 경로
def FilePath(instance, filename):
    # upload_to="%Y/%m/%d" 처럼 날짜로 세분화
    ymd_path = timezone.now().strftime('%Y/%m/%d')
    # 길이 32 인 uuid 값
    uuid_name = uuid4().hex
    # 확장자 추출
    extension = os.path.splitext(filename)[-1].lower()
    # 결합 후 return
    return '/'.join([ymd_path, uuid_name + extension])

# 공지사항 model
class Notice(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)  # 기존 모델을 속성으로 가져갈 경우 ForeignKey를 사용, on_delete=models.CASCADE 공지가 삭제 될 경우 삭제
    subject = models.CharField(max_length=100, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True) # null=True, blank=True을 사용하면 어떤 조건으로든 값을 비워둘수 있음
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='NoVoter')  # 추천인 기능 (Notice 모델에서 사용한 author와 voter가 모두 settings.AUTH_USER_MODEL모델로 참조되고 있기 때문에 related_name을 써주어야 함)
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):  # id 대신 제목을 표시
        return self.subject

    class Meta:
        db_table = "공지사항"
        verbose_name = "공지사항"
        verbose_name_plural = "공지사항"


# 질문 model
class Question(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='QVoter')
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):
        return self.subject

    class Meta:
        db_table = "질문게시판"
        verbose_name = "질문게시판"
        verbose_name_plural = "질문게시판"


# 답변 model
class Answer(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    question = models.ForeignKey(Question, verbose_name="질문아이디", on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='AVoter')

    class Meta:
        db_table = "질문에대한답변"
        verbose_name = "질문에대한답변"
        verbose_name_plural = "질문에대한답변"


# 영화 게시판 model
class Movie(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    subject = models.CharField(verbose_name="제목", max_length=100)
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='MoVoter')
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):
        return self.subject

    def delete(self, *args, **kargs):
        if self.upload_file:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_file.path))
        super(Movie, self).delete(*args, **kargs)

    class Meta:
        db_table = "영화게시판"
        verbose_name = "영화게시판"
        verbose_name_plural = "영화게시판"


# 게임 게시판 model
class Game(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    subject = models.CharField(verbose_name="제목", max_length=100)
    content = models.TextField(verbose_name="내용")
    hits = models.PositiveIntegerField(verbose_name="조회수", default=0)
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name="추천", related_name='GVoter')
    upload_file = models.FileField(verbose_name="파일", upload_to=FilePath, null=True, blank=True)
    file_subject = models.CharField(verbose_name="파일제목", max_length=64, null=True)

    def __str__(self):
        return self.subject

    class Meta:
        db_table = "게임게시판"
        verbose_name = "게임게시판"
        verbose_name_plural = "게임게시판"


# 댓글 model
class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="작성자", on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    create_date = models.DateTimeField(verbose_name="작성일시")
    modify_date = models.DateTimeField(verbose_name="수정일시", null=True, blank=True)
    question = models.ForeignKey(Question, verbose_name="질문댓글", null=True, blank=True, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, verbose_name="영화댓글", null=True, blank=True, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, verbose_name="게임댓글", null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        db_table = "댓글"
        verbose_name = "댓글"
        verbose_name_plural = "댓글"

myweb/myweb_main/views/GameViews.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import GameForm
from ..models import Game

import urllib
import os
from django.http import HttpResponse, Http404

# 내용 출력
def GameDetail(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    session_cookie = request.user
    cookie_name = f'game_hits:{session_cookie}'

    response = render(request, 'Game/game_detail.html', {'game': game})

    # 조회수 GET증가 방지 쿠키처리
    if request.COOKIES.get(cookie_name) is not None:
        cookies = request.COOKIES.get(cookie_name)
        cookies_list = cookies.split('|')
        if str(game_id) not in cookies_list:
            response.set_cookie(cookie_name, cookies + f'|{game_id}', expires=None)
            game.hits += 1
            game.save()
            return response

    else:
        response.set_cookie(cookie_name, game_id, expires=None)
        game.hits += 1
        game.save()
        return response
    return response

# 목록 출력
def GameList(request):
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지 값이 없을경우 디폴트 값은 1
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬하여 조회
    if so == 'recommend':
        game_list = Game.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        game_list = Game.objects.annotate(num_comment=Count('comment')).order_by('-num_comment', '-create_date')
    else:  # recent
        game_list = Game.objects.order_by('-create_date')

    # 검색
    if kw:
        game_list = game_list.filter(
            Q(subject__icontains=kw) |  # 제목검색 대소문자 구분 x (subject__contains=kw : 대소문자 구분)
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) # 글쓴이검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(game_list, 8)  # 페이지당 8개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'game_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'Game/game_list.html', context)

# 등록
@login_required(login_url='login:login')
def GameCreate(request):
    if request.method == 'POST':
        form = GameForm(request.POST, request.FILES)
        if form.is_valid():
            game = form.save(commit=False)
            game.author = request.user
            if request.FILES:
                if 'upload_file' in request.FILES.keys():
                    game.file_subject = request.FILES['upload_file'].name
            game.create_date = timezone.now()
            game.save()
            return redirect('myweb:GList')
    else:
        form = GameForm
    return render(request, 'Post/post_create.html', {'form': form})

# 수정
@login_required(login_url='login:login')
def GameModify(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    if request.user != game.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('myweb:GDetail', game_id=game.id)

    if request.method == "POST":
        form = GameForm(request.POST, request.FILES, instance=game)
        if form.is_valid():
            game = form.save(commit=False)
            game.author = request.user
            if request.FILES: # 파일 등록
                if 'upload_file' in request.FILES.keys():
                    game.file_subject = request.FILES['upload_file'].name
            game.modify_date = timezone.now()  # 수정일시 저장
            game.save()
            return redirect('myweb:GDetail', game_id=game.id)
    else:
        form = GameForm(instance=game)
    return render(request, 'Post/post_create.html', {'form': form})

# 삭제
@login_required(login_url='login:login')
def GameDelete(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    if request.user != game.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('myweb:GDetail', movie_id=game.id)
    game.delete()
    return redirect('myweb:GList')

# 파일 다운로드
@login_required(login_url='login:login')
def GameFileDownload(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    url = game.upload_file.url[1:]

    if os.path.exists(url):
        with open(url, 'rb') as fh:
            quote_file_url = urllib.parse.quote(game.file_subject.encode('utf-8'))
            response = HttpResponse(fh.read())
            response['Content-Disposition'] = 'attachment;filename*=UTF-8\'\'%s' % quote_file_url
            return response
        raise Http404

myweb/templates/Game/game_detail.html
{% extends "main/base.html" %}
{% block title %} game_detail.html {% endblock title %}
{% block content %}
    <!-- 사용자 오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}

    <h2 class="border-bottom ml-3 py-2">{{ game.subject }}</h2>
    <div class="row my-3">
        <!-- 질문 -->
        <div class="col-11" style="float:none; margin:0 auto">
            <div class="card">
                <div class="shadow card-body">
                    <div class="d-flex justify-content-start">
                        <h5 class="mr-2">{{ game.author.username }}</h5>
                        {% if game.modify_date %}
                        <p><small>(수정 : {{ game.modify_date | date:'Y-m-d H:i:s' }})</small></p>
                        {% else %}
                        <p><small>({{ game.create_date | date:'Y-m-d H:i:s' }})</small></p>
                        {% endif %}

                        <div class="ml-auto">
                            추천수&nbsp;:&nbsp;{{ game.voter.count }}&nbsp;
                            조회수&nbsp;:&nbsp;{{ game.hits }}
                        </div>
                    </div>
                    {% if game.upload_file %}
                    <div class="text-right">
                        <span>첨부파일&nbsp;:&nbsp;</span>
                        <a href="{% url 'myweb:GFileDownload' game.id %}" >{{ game.file_subject | truncatechars:20 }}</a>
                    </div>
                    {% endif %}

                    <div class="card-text">{{ game.content | safe }}</div>

                    <div class="d-flex justify-content-end">
                    <a href="#" data-uri="{% url 'myweb:GVote' game.id  %}" class="recommend btn btn-outline-secondary mr-2">추천</a>
                    {% if request.user == game.author %}
                        <a href="{% url 'myweb:GModify' game.id  %}" class="btn btn-outline-secondary ">수정</a>
                        <a href="#" class="delete btn btn-outline-secondary mx-2" data-uri="{% url 'myweb:GDelete' game.id  %}">삭제</a>
                    {% endif %}
                    <a href="{% url 'myweb:GList' %}"class="btn btn-outline-secondary">목록</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom ml-3 py-2">{{ game.comment_set.count }}&nbsp;개의 댓글이 있습니다.</h5>
    <div class="row my-3">
        <div class="col-11 mt-3" style="float:none; margin:0 auto">
            <div class="shadow card">
                <div id="more_comment">
                <!-- 댓글 -->
                {% if game.comment_set.count > 0 %}
                {% for comment in game.comment_set.all %}
                <a name="comment_{{ comment.id }}"></a>
                <div class="border-bottom">
                    <div class="mx-3 my-3">
                        <div class="d-flex justify-content-start">
                            <h5 class="mr-2">{{ comment.author }}</h5>
                            {% if comment.modify_date %}
                            <p><small>(수정 : {{ comment.modify_date | date:'Y-m-d H:i:s' }})</small></p>
                            {% else %}
                            <p><small>{{ comment.create_date | date:'Y-m-d H:i:s' }}</small></p>
                            {% endif %}
                        </div>

                        <span>{{ comment.content | linebreaksbr }}</span>
                    </div>

                    {% if request.user == comment.author %}
                    <div class="d-flex justify-content-end my-3">
                        <a href="{% url 'myweb:CommentModifyGame' comment.id %}" class="btn btn-outline-secondary mr-2">수정</a>
                        <a href="#" class="delete btn btn-outline-secondary mr-3" data-uri="{% url 'myweb:CommentDeleteGame' comment.id  %}">삭제</a>
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
                {% endif %}
                </div>

                <!-- 댓글 접기, 펼치기 -->
                {% if game.comment_set.count %}
                <div id="hide_more_button" style="cursor:pointer;">
                    <a id=hide_button_count>&nbsp;댓글 접기 &middot;&nbsp;{{ game.comment_set.count }}개의 댓글<br></a>
                </div>
                <div id="show_more_button" style="display:none;cursor:pointer;">
                    <a id="show_button_count">&nbsp;댓글 펼치기 &middot;&nbsp;{{ game.comment_set.count }}개의 댓글<br></a>
                </div>
                {% else %}
                <div id="hide_more_button" style="cursor:pointer;">
                    <a id=hide_button_count><br></a>
                </div>
                <div id="show_more_button" style="display:none;cursor:pointer;">
                    <a id="show_button_count"><br></a>
                </div>
                {% endif %}

                <!-- 댓글 양식 -->
                <div class="container my-3">
                    <form action="{% url 'myweb:CommentCreateGame' game.id %}" method="post" class="my-3">
                        {% csrf_token %}
                        {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {% for field in form %}
                            {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                            {% endif %}
                            {% endfor %}
                        </div>
                        {% endif %}
                        <div class="form-group">
                <textarea {% if not user.is_authenticated %}disabled{% endif %}
                          name="content" id="con" class="form-control" rows="2"></textarea>
                        </div>
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-outline-secondary">등록</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() { // 삭제 버튼
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() { // 추천 버튼
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $('#hide_more_button').click(function(){ // 댓글 접기
        $('#more_comment').hide();
        $('#show_more_button').show();
        $('#hide_more_button').hide();
    });
    $('#show_more_button').click(function(){ // 댓글 펼치기
        $('#more_comment').show();
        $('#show_more_button').hide();
        $('#hide_more_button').show();
    });
});
</script>
{% endblock %}

myweb/templates/Game/game_list.html
{% extends "main/base.html" %}
{% block title %} game_list.html {% endblock title %}
{% load myweb_filter %}
{% block content %}
<div class="container">
    <div class="row justify-content-between my-3">
        <!--정렬-->
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
                <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>
                <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>
            </select>
        </div>
        <!--찾기-->
        <div class="input-group col-4">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>

    <table class="table table-bordered table-hover">
        <thead>
        <tr class="text-center thead-light">
            <th>번호</th>
            <th>추천</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
            <th>조회수</th>
        </tr>
        </thead>
        <tbody>
        {% if game_list %}
        {% for game in game_list %}
        <tr class="text-center clickAble" style="cursor:pointer;" data-href="{% url 'myweb:GDetail' game.id %}">
            <td>
                <!--게시글 번호 -> 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ game_list.paginator.count|sub:game_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <!-- 추천 -->
            <td>
                {% if game.voter.all.count > 0 %}
                <span class="badge badge-warning px-2 py-1">{{ game.voter.all.count }}</span>
                {% endif %}
            </td>

            <td class="text-left">
                {{ game.subject | truncatechars:40 }}
                {% if game.comment_set.count > 0 %}
                <span class="text-danger small ml-2">{{ game.comment_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ game.author.username }}</td>
            <td>{{ game.create_date | date:'Y-m-d H:i' }}</td>
            <td>{{ game.hits }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="6">게시글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <div class="d-flex justify-content-end">
        <a href="{% url 'myweb:GCreate' %}" class="btn btn-outline-secondary">게시글 작성</a>
    </div>

    <!-- 페이징처리 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if game_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ game_list.previous_page_number }}" href="#">&laquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">&laquo;</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in game_list.paginator.page_range %}
        <!-- 5만큼 작은 것 부터 5만큼 큰 것 까지만 표시 -->
        {% if page_number >= game_list.number|add:-5 and page_number <= game_list.number|add:5 %}
        {% if page_number == game_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if game_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ game_list.next_page_number }}" href="#">&raquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">&raquo;</a>
        </li>
        {% endif %}
    </ul>
</div>
<!--검색, 정렬 폼-->
<form id="searchForm" method="get" action="{% url 'myweb:GList' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() { // page-link 클릭 시 스크립트 실행
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    $("#btn_search").on('click', function() { // 검색버튼을 클릭하면 검색어 텍스트창에 입력된 값을 폼 kw필드에 설정하여 폼을 요청
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    $(".so").on('change', function() { // so라는 클래스를 가지고 있는 select박스의 값이 변경되면 선택된 값을 so 필드에 설정하여 폼 요청
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
    $(document).on('click','.clickAble',function() {
    window.location=$(this).data("href");
    });
});
</script>
{% endblock %}